### ISSUE TITLE
TypeError involving margins when to_streamlit() is used

### ISSUE THREAD

**Issue by sowmyamanojna** [kamicollo/idendrogram#15] opened 2024-02-23 08:55 UTC
Thank you for the amazing package.

I'm trying to reproduce the code under the [Streamlit usage](https://kamicollo.github.io/idendrogram/streamlit/) section and I'm getting a `TypeError: convert() missing 1 required positional argument: 'margins'`.

I tried to overcome this by passing the margins as an argument to the [`to_streamlit()` function](https://github.com/kamicollo/idendrogram/blob/481f8193bf890b046d357b66e0b9e37c168b0a18/idendrogram/targets/streamlit.py#L34). But, I found that `margins` is not supported as an argument. I went through the code in [`idendrogram-streamlit` and saw that `margins` is `Optional`](https://github.com/kamicollo/idendrogram-streamlit/blob/4057a099e7c7c91f86466c3bc720f2a21501368f/idendrogram_streamlit_component/__init__.py#L38) and that [defaults are defined](https://github.com/kamicollo/idendrogram-streamlit/blob/4057a099e7c7c91f86466c3bc720f2a21501368f/idendrogram_streamlit_component/__init__.py#L45). But, I'm not sure how or why the error occurs.

Code to reproduce the error:
```python
import idendrogram
import scipy.cluster.hierarchy as sch
from idendrogram.targets.streamlit import to_streamlit

from sklearn.datasets import load_iris
data = load_iris()

#cluster the data
linkage_matrix = sch.linkage(
    data['data'], method='single', metric='euclidean'
)
threshold = 0.8
flat_clusters = sch.fcluster(
    linkage_matrix, t=threshold, criterion='distance'
)

#wrap clustering outputs / parameters into a container
cl_data = idendrogram.ClusteringData(
    linkage_matrix = linkage_matrix, 
    cluster_assignments = flat_clusters
)

#pass to idendrogram and create a dendrogram object
idd = idendrogram.idendrogram()
idd.set_cluster_info(cl_data)
dendrogram = idd.create_dendrogram(truncate_mode='level', p=10)

#visualize in streamlit and get the data object behind the selected node
selected_node = to_streamlit(dendrogram=dendrogram, height=200, width=629)
```

Any help on how to solve this would be extremely appreciated! Thanks!!

**Comment by kamicollo** [comment] 2024-02-24 02:26
@sowmyamanojna - thank you for reporting this. It seems I forgot to update the main package to reflect the changes in the Streamlit component API. I'll fix and release an updated version, but in the meantime, you can get it working by replacing the `to_streamlit` method with a bit more boilerplate code. Here's your example that should work:

```python
import idendrogram
import scipy.cluster.hierarchy as sch
from idendrogram_streamlit_component import StreamlitConverter
import streamlit as st

from sklearn.datasets import load_iris

data = load_iris()

# cluster the data
linkage_matrix = sch.linkage(data["data"], method="single", metric="euclidean")
threshold = 0.8
flat_clusters = sch.fcluster(linkage_matrix, t=threshold, criterion="distance")

# wrap clustering outputs / parameters into a container
cl_data = idendrogram.ClusteringData(
    linkage_matrix=linkage_matrix, cluster_assignments=flat_clusters
)

# pass to idendrogram and create a dendrogram object
idd = idendrogram.idendrogram()
idd.set_cluster_info(cl_data)
dendrogram = idd.create_dendrogram(truncate_mode="level", p=10)

# visualize in streamlit and get the data object behind the selected node
converter = StreamlitConverter(release=True)
selected_node = converter.convert(
    dendrogram,
    height=500,
    width=500,
    scale="linear",
    key="idendrogram",
    orientation="top",
    show_nodes=True,
    margins={"top": 50, "bottom": 50, "left": 50, "right": 50},
)

st.write(selected_node)
```

**Comment by kamicollo** [comment] 2024-02-24 02:43
The issue is now fixed. Upgrading to version `0.2.5` of `idendrogram-streamlit-component ` will resolve it and the previous code should work as intended, too. Fixed by **https://github.com/kamicollo/idendrogram-streamlit/pull/1**

**Closed as completed** 2024-02-24 02:44 UTC
Labels: bug

**Comment by sowmyamanojna** [comment] 2024-02-24 05:37
That's amazing. Thank you so much!
